### ISSUE TITLE
Releasing never-before-released project fails

### ISSUE THREAD

**Issue by Swatinem** [getsentry/craft#413] opened 2022-09-02 13:10 UTC
### Steps to Reproduce

1. Create a completely new project that has no tags and was never released previously
2. try to prepare a release with craft

### Expected Result

Craft should happily release this without any problems

### Actual Result

This here fails:

https://github.com/getsentry/craft/blob/9109b73950b408eaae380607c9a709e4e6aad5d5/src/commands/prepare.ts#L500

The git command fails with:

```
fatal: No names found, cannot describe anything.
```

Even if not, `oldVersion` would be empty/non-existant.

Happened here: https://github.com/getsentry/watto/runs/8156452454?check_suite_focus=true

**Comment by BYK** [comment] 2022-09-02 13:18
Looks like a duplicate of #342 to me?

**Comment by Swatinem** [comment] 2022-09-02 13:58
Ah absolutely. Well, looks like I was too overeager.

**Closed** 2022-09-06 13:14 UTC
