### ISSUE TITLE
Last step of publish is selecting the wrong merge target

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/craft#327] opened 2021-11-16 00:49 UTC
After a release we merge the release branch back to the base branch:

https://github.com/getsentry/craft/blob/78d2ca9c4bae075ce45ca888b94c86e176d9848f/src/commands/publish.ts#L331-L363

Unfortunately it looks like our algorithm for determining which branch to merge into if not explicitly provided is wrong. The past two `sentry` releases have merged back into the wrong branch:

https://github.com/getsentry/publish/runs/4218472116?check_suite_focus=true#step:8:123 &rarr; https://github.com/getsentry/sentry/commit/9ae170c4b3b2fd608caabb37e9ce08281d5e4747

https://github.com/getsentry/publish/runs/3909141316?check_suite_focus=true#step:8:666 &rarr;
https://github.com/getsentry/sentry/commit/b15920f0c741c35f70dab85b3b2b76ffa0317602

The result is that (at least) the CHANGES file in the sentry repo has not been updated since 21.9.0 ... we're missing all of the new changelog-y goodness!

https://github.com/getsentry/sentry/blob/master/CHANGES

**Comment by chadwhitacre** [comment] 2021-12-15 18:37
I'm pretty sure this is because `master` moves so quickly.

<img width="978" alt="Screen Shot 2021-12-15 at 10 35 43 AM" src="https://user-images.githubusercontent.com/134455/146245296-3fb2a078-e818-4a13-8224-417d040badd6.png">

**Comment by chadwhitacre** [comment] 2021-12-15 18:38
There is a CLI option. Can we use that for `sentry`? 🧐

https://github.com/getsentry/craft/blob/95677da7d2f8c15df19cf1bd6369bdeb77209b3b/src/commands/publish.ts#L75-L80

**Comment by chadwhitacre** [comment] 2021-12-15 18:39
Hrm, [not easily](https://github.com/getsentry/publish/blob/b229c878e97fe7529e809b1646fe5f57bab0d9aa/.github/workflows/publish.yml#L57). 🤔

**Comment by BYK** [comment] 2021-12-15 19:01
@chadwhitacre you can probably make "Uses the default branch from GitHub as a fallback" case the default and move the current logic into `-m auto`?

**Comment by chadwhitacre** [comment] 2021-12-15 19:39
@BYK That sounds more reasonable to me. What was the use-case for the `auto` strategy in the first place? Are there other craft users/projects that depend on that? 🤔

**Comment by BYK** [comment] 2021-12-15 19:52
>@BYK That sounds more reasonable to me. What was the use-case for the auto strategy in the first place? Are there other craft users/projects that depend on that? 🤔

There are some projects that release from custom branches for RC, beta, and hotfix releases and this was to address those use cases.

An alternative would be to add this as an option to the config file instead of a CLI argument. This way projects can easily control the behavior?

**Comment by chadwhitacre** [comment] 2021-12-15 20:22
> An alternative would be to add this as an option to the config file instead of a CLI argument. This way projects can easily control the behavior?

That's more along the lines of what I was thinking. Basically any option that craft accepts on the command line should be available through the config file.

**Comment by BYK** [comment] 2021-12-15 20:29
> Basically any option that craft accepts on the command line should be available through the config file.

I dare you to make that happen 🤣 Remember how https://github.com/getsentry/craft/pull/235 went?

**Comment by BYK** [comment] 2021-12-16 07:52
Thinking of this again, since the issue is master moving too quickly, I think another `pull` right before trying to determine the target should fix the issue mostly?

**Comment by jan-auer** [comment] 2021-12-20 15:54
We just hit this same bug with `sentry-native`, see https://github.com/getsentry/publish/issues/694#issuecomment-997978039

The culprit here is the following:
- There's a branch ref pointing directly to an old commit on the `master` branch
- The release branch has been branched off _after_ that commit
- Craft uses `git log --decorate --simplify-by-decoration --oneline`, which doesn't see the branch point
- It finds that old ref and uses it as a base branch.

I haven't had the chance to look into this much further. We would basically need to find the branching point rather than searching for refs in the log. Same when the base branch moves on in the meanwhile, which is what happened for the Sentry release.

**Comment by jan-auer** [comment] 2021-12-22 14:05
@BYK is that something you remember considering initially, or any gotchas on your end before i go down the rabbit hole?

**Comment by BYK** [comment] 2021-12-22 15:31
>@BYK is that something you remember considering initially, or any gotchas on your end before i go down the rabbit hole?

@jan-auer I chose the current method in https://stackoverflow.com/a/55238339/90297 due to the reasons they listed under "Why did not show-branch work for me". I did not encounter them but the last case kind of looked possible (develop vs master for hotfixes). I think we can try the other approach and see if it actually gives us any headaches.

**Comment by jan-auer** [comment] 2021-12-23 09:28
Spent a little bit of time playing with this and I believe the best overall solution would be to remove this feature from craft and instead always merge into the default branch when no merge base is given via CLI. We can make this a "branch to merge into (leave empty for default branch)" argument on the release action, which should be bullet proof.

---

Next, let's address all the points from the stackoverflow answer explaining why `show-branch` wouldn't work:

> - detached HEAD – including detached head case means replacing `grep '\*' \` for `grep '!' \` – and that is just the beginning of all the troubles

By definition, we always have a release branch that we need to track to its parent branch. Detached head does not make sense for our problem statement. That said, given we can write procedural code, it would be rather straight forward to use the extended ref (e.g. `development~2`) to track down the correct branch. This is only a problem if you need to do all of this in the shell.

> - running the script on `master` and `develop` results in develop and `""` respectively

That is precisely what we want. And here again, we would never run this on `master`. 

> - branches on `master` branch (`hotfix/` branches) end up with the `develop` as a parent since their closest `master` branch parent was marked with `!` instead of `*` for a reason.

I believe that this was a bug in parsing the output through grep / awk. `!` is only used to list current heads in the output, but not for the commit list after `---`. 

---

If we want to keep this functionality around, then I think the `show-branch` based solution should be more reliable for us. This way, one doesn't have to deal with old heads (branches pointing to a master commit) and tags. 

There's only **a single case** that I was able to find where `show-branch` outputs the wrong branch: If the latest master commit is _also_ pointed to by a branch without own commits. For example:

```
 A---B---D <- master, feat/something
      \
       \
        C <- release/1.2.3

```

In that case, show-branch would choose `feat/something` rather than `master`.

**Comment by BYK** [comment] 2021-12-23 14:55
>There's only a single case that I was able to find where show-branch outputs the wrong branch: If the latest master commit is also pointed to by a branch without own commits. For example:

I think we can easily detect this case and prefer `master` or just throw an exception saying "ambitious branch to merge to".

>I believe the best overall solution would be to remove this feature from craft and instead always merge into the default branch when no merge base is given via CLI

I think this is not very intuitive. We may at least want to _require_ an explicit flag to be passed when/if we detect a "non-standard" branch.

**Comment by chadwhitacre** [comment] 2021-12-23 17:26
> when/if we detect a "non-standard" branch.

I thought @jan-auer's suggestion is that we no longer do any branch detection. We either merge to the default branch or to an explicitly specified branch. Basically https://github.com/getsentry/craft/issues/327#issuecomment-995093835 but `s/-m auto/-m mybranch`. No?

> If we want to keep this [automatic branch detection] functionality around

👎

> remove this feature from craft and instead always merge into the default branch when no merge base is given via CLI

👍

**Comment by chadwhitacre** [comment] 2021-12-28 19:11
For the record #245 is where we introduced merge branch detection. I'm a little confused how this relates to #223.

**Comment by jan-auer** [comment] 2022-01-17 22:22
This happened again, unfortunately, and I didn't even notice it until I accidentally stumbled across the changelog entry missing. Craft selects the wrong target and there's not even a big warning or anything. Given that we merge into the main branch in almost every case, this is another +1 for me to back this feature out and make it manual. At least then it's intentional.

**Comment by bruno-garcia** [comment] 2022-02-15 13:04
We hit this on `sentry-unity`. 👍  here to help prioritize.

**Comment by chadwhitacre** [comment] 2022-02-15 13:47
Bummer. I'll probably hit this today with self-hosted 22.2.0. :-/

This is an action item on [INC-95](https://www.notion.so/sentry/INC-95-Self-Hosted-Release-22-1-0-Delayed-9efa2117dc2c4226a72b5b06c98bea0c). @jan-auer Once I get through https://github.com/getsentry/publish/issues/666 I would be happy to look into this as well if need be.

**Closed** 2022-03-01 15:42 UTC
Labels: bug
