### ISSUE TITLE
Changelog breaks on first release

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/craft#395] opened 2022-05-16 22:11 UTC
Coming here from https://github.com/getsentry/develop/issues/579. With latest craft, `getLatestTag` throws an error if there isn't already a tag on the default branch (or, I guess, whatever branch you're preparing the release from), which is the case for the first release in a project (and also the case if your repo is corrupted, which seems to be the case in https://github.com/getsentry/develop/issues/579). In this case the changelog should presumably be constructed from all commits to date.

**Comment by kamilogorek** [comment] 2022-05-17 08:21
Duplicate of https://github.com/getsentry/craft/issues/342

**Closed by kamilogorek** 2022-05-17 08:21 UTC
Labels: bug

**Comment by chadwhitacre** [comment] 2022-05-17 13:22
lolsob
